### ISSUE TITLE
OS-X specific files committed to the repository

### ISSUE THREAD

**Issue by andreas-kupries** [Dash-OS/cluster-comm#2]
Do we really want ` 	.DS_Store` files in the repository ?

Not sure if this leaks private information; even if not I don't think it is information a builder or other person making a checkout will need.

**Comment by bradennapier** [comment]
Hm, thought I had gotten all of them out.  I'll run through again to double check.  Ok done.  In the process of releasing most of our build system so few little pieces making it through the crack.  This one was missing the .gitignore.
